["add", "+", "return"]
["subtract", "-"]
["multiply", "*"]
["divide", "/"]
["document.getElementById(", "addEventListener"]
["parseFloat", "value"] / calculator.js doesn't contain: ["parseFloat", "value"]
["textContent"]
