  ["checkAnswer"]           
["correctAnswer", "4"]
["document.querySelector", "quiz", "checked", "value"] / quiz.js doesn't contain: ["userAnswer"]
["if (userAnswer === correctAnswer)"]
["document.querySelector("] / quiz.js doesn't contain: ["Correct! Well done."]
["That's incorrect. Try again!"]
["addEventListener("]
["document.getElementById("]
